# Example config values for osim client

# COLLECTION or GRANULE
metadata_type: GRANULE

# Kafka config values
brokers: onestop-dev-cp-kafka:9092
schema_registry: http://onestop-dev-cp-schema-registry:8081
collection_topic_produce: psi-granules-by-collection
granule_topic_produce: psi-granule-parsed
collection_topic_consume: psi-collection-input-unknown
granule_topic_consume: psi-granule-input-unknown
group_id: sme-test
auto_offset_reset: earliest

security:
  enabled: False
  caLoc: /etc/pki/tls/cert.pem
  keyLoc: /etc/pki/tls/private/kafka-user.key
  certLoc: /etc/pki/tls/certs/kafka-user.crt