# Example config values for osim client

# COLLECTION or GRANULE
metadata_type: granule
registry_base_url: https://localhost/onestop/api/registry
onestop_base_url: https://ab76afcf90ee844ea95ba43a75c3624c-1204932138.us-east-1.elb.amazonaws.com/onestop-search/search
#registry_base_url: http://internal-aedcb94123a514f679c943e66cb7d3c0-979069726.us-east-1.elb.amazonaws.com
#onestop_base_url: http://internal-aedcb94123a514f679c943e66cb7d3c0-979069726.us-east-1.elb.amazonaws.com/onestop-search/search

security:
  enabled: True

prefixMap:
  NESDIS/CSB: 'fdb56230-87f4-49f2-ab83-104cfd073177'
  NESDIS/H8: '0fad03df-0805-434a-86a6-7dc42d68480e'
  NESDIS/GOES: '11111111-1111-1111-1111-111111111111'
  NESDIS/SAB: '98e03b47-069a-4f2c-8071-649e8c4254d6'