apiVersion: v1
kind: Pod
metadata:
  name: onestop-pyconsumer
spec:
  containers:
  - name: onestop-pyconsumer
    tty: true #need this to get the output with `kubectl logs onestop-pyconsumer`
    image: cedardevs/onestop-pyconsumer:latest
    imagePullPolicy: Always

