# Default values for onestop-sqs-consumer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cedardevs/onestop-s3-handler
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

#aws:
#  region: <region in which the sqs queue exists>

#sqs:
#  queue:
#    url: 
#registry:
#  endpoint:

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaler:
  enabled: false
  #minReplicas: 
  #maxReplicas:
  #metrics: []

nodeSelector: {}

tolerations: []

affinity: {}

secret:
  registry_username: <value>
  registry_password: <value>
  access_key: <value>
  secret_key: <value>

config: |-
  ---
  log_level: INFO

  # AWS config values
  sqs_url: https://sqs.us-east-2.amazonaws.com/798276211865/cloud-archive-client-sqs
  sqs_max_polls: 100
  s3_region: us-east-2
  s3_bucket: archive-testing-demo

  #AWS config values for 2nd vault in different region
  vault_name: archive-vault-new
  s3_region2: us-east-2
  s3_bucket2: noaa-nccf-dev-archive

  #CSB stream config
  format: csv
  headers: UNIQUE_ID,FILE_UUID,LON,LAT,DEPTH,TIME,PLATFORM_NAME,PROVIDER
  type: COLLECTION
  collection_id: fdb56230-87f4-49f2-ab83-104cfd073177
  access_bucket: https://archive-testing-demo.s3-us-east-2.amazonaws.com
  #access_bucket: https://odp-noaa-nesdis-ncei-test.s3-us-west-2.amazonaws.com
  file_identifier_prefix: "gov.noaa.ncei.csb:"

  # COLLECTION or GRANULE
  metadata_type: granule
  registry_base_url: http://onestop-registry:80
  onestop_base_url: http://onestop-search:8080

  security:
    enabled: True
