jobs:
  cli-test:
    executor:
      name: go/default
      tag: '1.13'
    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: mkdir -p $TEST_RESULTS # create the test results directory
      - run: cd cli/; ls -la; pwd;
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "cli/go.sum" }}
      - go/test:
          covermode: atomic
          failfast: false
          race: true
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
# cli build
  cli-build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          dockerfile: /cli/Dockerfile
          image: cedardevs/onestop-cli
      - docker/push:
          digest-path: /tmp/digest.txt
          image: cedardevs/onestop-cli
# clients build
  client-build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          dockerfile: /example/Dockerfile
          image: cedardevs/onestop-client
            - docker/push:
#                digest-path: /tmp/digest.txt
#                image: cedardevs/onestop-cli

orbs:
  go: circleci/go@1.1.1
  docker: circleci/docker@1.0.1
version: 2.1
workflows:
  main:
    jobs:
      - cli-test
      - cli-build
      - client-build

