jobs:
  cli-test:
    executor:
      name: go/default
      tag: '1.13'
    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: mkdir -p $TEST_RESULTS # create the test results directory
      - run: cd cli/; ls -la; pwd;
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "cli/go.sum" }}
      - go/test:
          covermode: atomic
          failfast: false
          race: true
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - slack/status:
          fail_only: false

  cli-generation:
    executor:
      name: go/default
      tag: '1.13'
    environment:
      - GOOS: 'linux'
      - GOARCH: 'amd64'
      - GCO_ENABLED: 0
    working_directory: ~/cli
    steps:
      - checkout
      - run:
          name: generate openapi
          command: |
            echo "Generating CLI" &&
            cd cli &&
            go get -u github.com/danielgtaylor/openapi-cli-generator &&
            wget https://raw.githubusercontent.com/cedardevs/onestop/master/search/src/main/resources/static/openapi.yaml &&
            openapi-cli-generator generate openapi.yaml &&
            sed -i 's/package main/package generated/g' openapi.go &&
            sed -i 's/openapiRegister/OpenapiRegister/g' openapi.go &&
            mv openapi.go internal/app/generated/
      - persist_to_workspace:
          root: ~/cli
          paths:
            - cli/internal/app/generated/openapi.go

# cli build
  cli-build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: generate openapi go file
          command: |
            echo "copying openapi go" &&
            cd cli &&
            docker run golang go get -u github.com/danielgtaylor/openapi-cli-generator &&
            wget https://raw.githubusercontent.com/cedardevs/onestop/master/search/src/main/resources/static/openapi.yaml &&
            openapi-cli-generator generate openapi.yaml &&
            sed -i 's/package main/package generated/g' openapi.go
            sed -i 's/openapiRegister/OpenapiRegister/g' openapi.go &&
            mv openapi.go internal/app/generated/
      - docker/check
      - docker/build:
          path: cli
          image: cedardevs/onestop-cli
          tag: ${CIRCLE_BRANCH}-SNAPSHOT
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - docker/push:
          image: cedardevs/onestop-cli
          tag: ${CIRCLE_BRANCH}-SNAPSHOT
      - slack/status:
          fail_only: false


# clients build
  client-build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          path: examples
          image: cedardevs/python-client
          tag: ${CIRCLE_BRANCH}-SNAPSHOT
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
#no need to push this image yet
#      - docker/push:
#          image: cedardevs/python-client
#          tag: ${CIRCLE_BRANCH}-SNAPSHOT
      - slack/status:
          fail_only: false

orbs:
  slack: circleci/slack@3.4.2
  go: circleci/go@1.1.1
  docker: circleci/docker@1.0.1
version: 2.1
workflows:
  main:
    jobs:
      - cli-test
#      - cli-generation
      - cli-build
      - client-build

