# Example config values for osim client
log_level: INFO

# AWS config values
sqs_url: https://sqs.us-east-2.amazonaws.com/798276211865/cloud-archive-client-sqs
sqs_max_polls: 2
region: "us-east-2"
s3_bucket: archive-testing-demo
vault_name: archive-vault

#AWS config values for 2nd vault in different region
vault_name2: archive-vault-new
region2: "us-west-2"
