#Copy me as credentials.yml and update with values and exclude the file from git
#NESDIS-SANDBOX
sandbox:
  access_key: access_key_value_here
  secret_key: access_key_value_here

#Registry
registry:
  username: rw_user
  password: rw_user_pwd
