# Example config values for osim client
log_level: INFO

# COLLECTION or GRANULE
metadata_type: granule
registry_base_url: https://cedardevs.org/onestop/api/registry
onestop_base_url: https://ab76afcf90ee844ea95ba43a75c3624c-1204932138.us-east-1.elb.amazonaws.com/onestop-search/search

security:
  enabled: True

# Initial registry base_url https://ab76afcf90ee844ea95ba43a75c3624c-1204932138.us-east-1.elb.amazonaws.com/registry
