# Expect this to copy the scripts directory over and install onestop-python-client.
FROM cedardevs/onestop-python-client:latest

# Install additional python libraries needed by scripts
RUN pip install argparse
RUN pip install psycopg2

CMD tail -f /dev/null
