{{ if .Values.autoscaler.enabled -}}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "onestop-sqs-consumer.fullname" . }}
  {{- with .Values.autoscaler.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "onestop-sqs-consumer.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "onestop-sqs-consumer.fullname" . }}
  minReplicas: {{ .Values.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
{{- with .Values.autoscaler.metrics }}
  metrics: {{ toYaml . | nindent 2 }}
{{- end }}
{{- end }}

  {{/*
Use a common config name variable, rather than appending -config in several places.
*/}}
  {{- define "onestop-sme.configname" -}}
  {{ template "onestop-sme.fullname" . }}-config
{{- end -}}