---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onestop-sqs-consumer.fullname" . }}-secret
type: Opaque
stringData:
  registry_username: {{ .Values.secret.registry_username }}
  registry_password: {{ .Values.secret.registry_password }}
  access_key: {{ .Values.secret.access_key }}
  secret_key: {{ .Values.secret.secret_key }}